EC2_ENDPOINTS = {
    "americas": {
        "name": "Americas Regions",
        "endpoints": [
            {"name": "US East 1 (N. Virginia)", "ip": "ec2.us-east-1.amazonaws.com", "icon": "🇺🇸"},
            {"name": "US East 2 (Ohio)", "ip": "ec2.us-east-2.amazonaws.com", "icon": "🇺🇸"},
            {"name": "US West 1 (N. California)", "ip": "ec2.us-west-1.amazonaws.com", "icon": "🇺🇸"},
            {"name": "US West 2 (Oregon)", "ip": "ec2.us-west-2.amazonaws.com", "icon": "🇺🇸"},
            {"name": "Canada Central", "ip": "ec2.ca-central-1.amazonaws.com", "icon": "🇨🇦"},
            {"name": "Canada West", "ip": "ec2.ca-west-1.amazonaws.com", "icon": "🇨🇦"},
            {"name": "Mexico Central", "ip": "ec2.mx-central-1.amazonaws.com", "icon": "🇲🇽"},
            {"name": "South America (São Paulo)", "ip": "ec2.sa-east-1.amazonaws.com", "icon": "🇧🇷"},
        ],
    },
    "europe": {
        "name": "Europe Regions",
        "endpoints": [
            {"name": "Europe West 1 (Ireland)", "ip": "ec2.eu-west-1.amazonaws.com", "icon": "🇮🇪"},
            {"name": "Europe West 2 (London)", "ip": "ec2.eu-west-2.amazonaws.com", "icon": "🇬🇧"},
            {"name": "Europe West 3 (Paris)", "ip": "ec2.eu-west-3.amazonaws.com", "icon": "🇫🇷"},
            {"name": "Europe Central 1 (Frankfurt)", "ip": "ec2.eu-central-1.amazonaws.com", "icon": "🇩🇪"},
            {"name": "Europe Central 2 (Zurich)", "ip": "ec2.eu-central-2.amazonaws.com", "icon": "🇨🇭"},
            {"name": "Europe North 1 (Stockholm)", "ip": "ec2.eu-north-1.amazonaws.com", "icon": "🇸🇪"},
            {"name": "Europe South 1 (Milan)", "ip": "ec2.eu-south-1.amazonaws.com", "icon": "🇮🇹"},
            {"name": "Europe South 2 (Spain)", "ip": "ec2.eu-south-2.amazonaws.com", "icon": "🇪🇸"},
        ],
    },
    "asia_pacific": {
        "name": "Asia Pacific Regions",
        "endpoints": [
            {"name": "Asia Pacific Northeast 1 (Tokyo)", "ip": "ec2.ap-northeast-1.amazonaws.com", "icon": "🇯🇵"},
            {"name": "Asia Pacific Northeast 2 (Seoul)", "ip": "ec2.ap-northeast-2.amazonaws.com", "icon": "🇰🇷"},
            {"name": "Asia Pacific Northeast 3 (Osaka)", "ip": "ec2.ap-northeast-3.amazonaws.com", "icon": "🇯🇵"},
            {"name": "Asia Pacific Southeast 1 (Singapore)", "ip": "ec2.ap-southeast-1.amazonaws.com", "icon": "🇸🇬"},
            {"name": "Asia Pacific Southeast 2 (Sydney)", "ip": "ec2.ap-southeast-2.amazonaws.com", "icon": "🇦🇺"},
            {"name": "Asia Pacific Southeast 3 (Jakarta)", "ip": "ec2.ap-southeast-3.amazonaws.com", "icon": "🇮🇩"},
            {"name": "Asia Pacific Southeast 4 (Melbourne)", "ip": "ec2.ap-southeast-4.amazonaws.com", "icon": "🇦🇺"},
            {"name": "Asia Pacific Southeast 5 (Malaysia)", "ip": "ec2.ap-southeast-5.amazonaws.com", "icon": "🇲🇾"},
            {"name": "Asia Pacific Southeast 7 (Thailand)", "ip": "ec2.ap-southeast-7.amazonaws.com", "icon": "🇹🇭"},
            {"name": "Asia Pacific South 1 (Mumbai)", "ip": "ec2.ap-south-1.amazonaws.com", "icon": "🇮🇳"},
            {"name": "Asia Pacific South 2 (Hyderabad)", "ip": "ec2.ap-south-2.amazonaws.com", "icon": "🇮🇳"},
            {"name": "Asia Pacific East 1 (Hong Kong)", "ip": "ec2.ap-east-1.amazonaws.com", "icon": "🇭🇰"},
        ],
    },
    "middle_east_africa": {
        "name": "Middle East & Africa",
        "endpoints": [
            {"name": "Middle East Central 1 (UAE)", "ip": "ec2.me-central-1.amazonaws.com", "icon": "🇦🇪"},
            {"name": "Middle East South 1 (Bahrain)", "ip": "ec2.me-south-1.amazonaws.com", "icon": "🇧🇭"},
            {"name": "Israel Central 1 (Tel Aviv)", "ip": "ec2.il-central-1.amazonaws.com", "icon": "🇮🇱"},
            {"name": "Africa South 1 (Cape Town)", "ip": "ec2.af-south-1.amazonaws.com", "icon": "🇿🇦"},
        ],
    },
}

AZURE_ENDPOINTS = {
    "americas": {
        "name": "Americas Regions",
        "endpoints": [
            {"name": "East US", "endpoint": "eastus.blob.core.windows.net", "region": "eastus", "icon": "🇺🇸"},
            {"name": "East US 2", "endpoint": "eastus2.blob.core.windows.net", "region": "eastus2", "icon": "🇺🇸"},
            {"name": "Central US", "endpoint": "centralus.blob.core.windows.net", "region": "centralus", "icon": "🇺🇸"},
            {"name": "North Central US", "endpoint": "northcentralus.blob.core.windows.net", "region": "northcentralus", "icon": "🇺🇸"},
            {"name": "South Central US", "endpoint": "southcentralus.blob.core.windows.net", "region": "southcentralus", "icon": "🇺🇸"},
            {"name": "West Central US", "endpoint": "westcentralus.blob.core.windows.net", "region": "westcentralus", "icon": "🇺🇸"},
            {"name": "West US", "endpoint": "westus.blob.core.windows.net", "region": "westus", "icon": "🇺🇸"},
            {"name": "West US 2", "endpoint": "westus2.blob.core.windows.net", "region": "westus2", "icon": "🇺🇸"},
            {"name": "West US 3", "endpoint": "westus3.blob.core.windows.net", "region": "westus3", "icon": "🇺🇸"},
            {"name": "Canada Central", "endpoint": "canadacentral.blob.core.windows.net", "region": "canadacentral", "icon": "🇨🇦"},
            {"name": "Canada East", "endpoint": "canadaeast.blob.core.windows.net", "region": "canadaeast", "icon": "🇨🇦"},
            {"name": "Brazil South", "endpoint": "brazilsouth.blob.core.windows.net", "region": "brazilsouth", "icon": "🇧🇷"},
            {"name": "Brazil Southeast", "endpoint": "brazilsoutheast.blob.core.windows.net", "region": "brazilsoutheast", "icon": "🇧🇷"},
        ],
    },
    "europe": {
        "name": "Europe Regions",
        "endpoints": [
            {"name": "North Europe", "endpoint": "northeurope.blob.core.windows.net", "region": "northeurope", "icon": "🇮🇪"},
            {"name": "West Europe", "endpoint": "westeurope.blob.core.windows.net", "region": "westeurope", "icon": "🇳🇱"},
            {"name": "France Central", "endpoint": "francecentral.blob.core.windows.net", "region": "francecentral", "icon": "🇫🇷"},
            {"name": "France South", "endpoint": "francesouth.blob.core.windows.net", "region": "francesouth", "icon": "🇫🇷"},
            {"name": "Germany North", "endpoint": "germanynorth.blob.core.windows.net", "region": "germanynorth", "icon": "🇩🇪"},
            {"name": "Germany West Central", "endpoint": "germanywestcentral.blob.core.windows.net", "region": "germanywestcentral", "icon": "🇩🇪"},
            {"name": "Italy North", "endpoint": "italynorth.blob.core.windows.net", "region": "italynorth", "icon": "🇮🇹"},
            {"name": "Norway East", "endpoint": "norwayeast.blob.core.windows.net", "region": "norwayeast", "icon": "🇳🇴"},
            {"name": "Norway West", "endpoint": "norwaywest.blob.core.windows.net", "region": "norwaywest", "icon": "🇳🇴"},
            {"name": "Poland Central", "endpoint": "polandcentral.blob.core.windows.net", "region": "polandcentral", "icon": "🇵🇱"},
            {"name": "Spain Central", "endpoint": "spaincentral.blob.core.windows.net", "region": "spaincentral", "icon": "🇪🇸"},
            {"name": "Sweden Central", "endpoint": "swedencentral.blob.core.windows.net", "region": "swedencentral", "icon": "🇸🇪"},
            {"name": "Sweden South", "endpoint": "swedensouth.blob.core.windows.net", "region": "swedensouth", "icon": "🇸🇪"},
            {"name": "Switzerland North", "endpoint": "switzerlandnorth.blob.core.windows.net", "region": "switzerlandnorth", "icon": "🇨🇭"},
            {"name": "Switzerland West", "endpoint": "switzerlandwest.blob.core.windows.net", "region": "switzerlandwest", "icon": "🇨🇭"},
            {"name": "UK South", "endpoint": "uksouth.blob.core.windows.net", "region": "uksouth", "icon": "🇬🇧"},
            {"name": "UK West", "endpoint": "ukwest.blob.core.windows.net", "region": "ukwest", "icon": "🇬🇧"},
        ],
    },
    "asia_pacific": {
        "name": "Asia Pacific Regions",
        "endpoints": [
            {"name": "East Asia", "endpoint": "eastasia.blob.core.windows.net", "region": "eastasia", "icon": "🇭🇰"},
            {"name": "Southeast Asia", "endpoint": "southeastasia.blob.core.windows.net", "region": "southeastasia", "icon": "🇸🇬"},
            {"name": "Australia Central", "endpoint": "australiacentral.blob.core.windows.net", "region": "australiacentral", "icon": "🇦🇺"},
            {"name": "Australia Central 2", "endpoint": "australiacentral2.blob.core.windows.net", "region": "australiacentral2", "icon": "🇦🇺"},
            {"name": "Australia East", "endpoint": "australiaeast.blob.core.windows.net", "region": "australiaeast", "icon": "🇦🇺"},
            {"name": "Australia Southeast", "endpoint": "australiasoutheast.blob.core.windows.net", "region": "australiasoutheast", "icon": "🇦🇺"},
            {"name": "Central India", "endpoint": "centralindia.blob.core.windows.net", "region": "centralindia", "icon": "🇮🇳"},
            {"name": "South India", "endpoint": "southindia.blob.core.windows.net", "region": "southindia", "icon": "🇮🇳"},
            {"name": "West India", "endpoint": "westindia.blob.core.windows.net", "region": "westindia", "icon": "🇮🇳"},
            {"name": "Japan East", "endpoint": "japaneast.blob.core.windows.net", "region": "japaneast", "icon": "🇯🇵"},
            {"name": "Japan West", "endpoint": "japanwest.blob.core.windows.net", "region": "japanwest", "icon": "🇯🇵"},
            {"name": "Korea Central", "endpoint": "koreacentral.blob.core.windows.net", "region": "koreacentral", "icon": "🇰🇷"},
            {"name": "Korea South", "endpoint": "koreasouth.blob.core.windows.net", "region": "koreasouth", "icon": "🇰🇷"},
        ],
    },
    "middle_east_africa": {
        "name": "Middle East & Africa",
        "endpoints": [
            {"name": "UAE Central", "endpoint": "uaecentral.blob.core.windows.net", "region": "uaecentral", "icon": "🇦🇪"},
            {"name": "UAE North", "endpoint": "uaenorth.blob.core.windows.net", "region": "uaenorth", "icon": "🇦🇪"},
            {"name": "South Africa North", "endpoint": "southafricanorth.blob.core.windows.net", "region": "southafricanorth", "icon": "🇿🇦"},
            {"name": "South Africa West", "endpoint": "southafricawest.blob.core.windows.net", "region": "southafricawest", "icon": "🇿🇦"},
            {"name": "Israel Central", "endpoint": "israelcentral.blob.core.windows.net", "region": "israelcentral", "icon": "🇮🇱"},
            {"name": "Qatar Central", "endpoint": "qatarcentral.blob.core.windows.net", "region": "qatarcentral", "icon": "🇶🇦"},
        ],
    },
}
